@extends('layouts.public')
@section('title', 'Membership application')
@section('content')
@php
    $applicationErrorKeys = collect($errors->keys());
    $chosenPackageId = old('membership_package_id', $draft?->membership_package_id ?? $selectedPackageId);
    $chosenPackage = $packages->firstWhere('id', (int) $chosenPackageId);
    $isPremiumPackage = in_array($chosenPackage?->slug, ['gold', 'platinum'], true);
    $applicationStep = $errors->hasAny(['full_name', 'email', 'phone']) ? 1
        : ($applicationErrorKeys->contains(fn ($key) => str_starts_with($key, 'references.')) ? 2
        : ($errors->hasAny(['company_description', 'employee_count', 'company_profile_file']) ? 5
        : ($errors->hasAny(['company', 'job_title', 'industry', 'location', 'biography']) ? 3
        : ($errors->hasAny(['membership_package_id', 'consent']) ? 4 : 1))));
@endphp
<section class="application-intro">
    <div class="application-intro-inner">
        <div class="application-intro-copy"><p class="eyebrow"><span class="eyebrow-line"></span>Membership / Application</p><h1>Begin with<br><em>your story.</em></h1><p>Tell us about yourself, your work and the two current members who will support your application.</p></div>
        <aside class="application-prep-note"><span>Before you begin</span><p>Please have contact details for two current members who know you and your work.</p><div class="application-meta"><span>About 8 minutes</span><span>4 clear steps</span><span>Private submission</span></div></aside>
    </div>
</section>
<section class="application-shell" x-ref="applicationTop" x-data="{step: {{ $applicationStep }}, isPremium(){ return ['gold','platinum'].includes(document.querySelector('#package')?.selectedOptions[0]?.dataset.slug); }, goTo(target){ this.step = target; this.$nextTick(() => { const panel = this.$refs['step' + target]; panel?.querySelector('h2')?.focus({preventScroll: true}); this.$refs.applicationTop.scrollIntoView({block: 'start', behavior: 'smooth'}); }); }, next(){ const fields = [...this.$refs['step' + this.step].querySelectorAll('input,select,textarea')]; const invalid = fields.find(el => !el.checkValidity()); if(invalid){ invalid.reportValidity(); return; } if(this.step === 4 && this.isPremium()){ this.goTo(5); return; } this.goTo(Math.min(4, this.step + 1)); }, back(){ this.goTo(Math.max(1, this.step - 1)); }}" @if($errors->any()) x-init="$nextTick(() => { $refs.applicationTop.scrollIntoView({block: 'start'}); $refs.validationSummary?.focus({preventScroll: true}); })" @endif>
    <div class="application-shell-inner">
    <ol class="wizard-progress" aria-label="Application progress">
        <template x-for="(label, index) in (isPremium() ? ['Your details','Member references','Professional profile','Review','Company profile'] : ['Your details','Member references','Professional profile','Review'])" :key="index"><li class="wizard-step" :class="{'is-current': step === index + 1, 'is-complete': step > index + 1}" :aria-current="step === index + 1 ? 'step' : null" :aria-label="label + (step === index + 1 ? ' (current step)' : step > index + 1 ? ' (completed)' : '')"><span x-text="step > index + 1 ? '✓' : '0' + (index + 1)"></span><b x-text="label"></b></li></template>
    </ol>
    @if($errors->any())<div x-ref="validationSummary" class="validation-summary" role="alert" tabindex="-1"><strong>Please review the application details.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" enctype="multipart/form-data" action="{{ route('application.store') }}" x-ref="panel" novalidate @submit="if (step < 4 || (step === 4 && isPremium() && $event.submitter?.name !== 'save_draft')) { $event.preventDefault(); next(); } else if ($event.submitter?.name !== 'save_draft' && !$refs.consent.checked) { $event.preventDefault(); $refs.consent.setCustomValidity('Please confirm the application review consent to submit.'); $refs.consent.reportValidity(); }">
        @csrf
        @if($draft)<input type="hidden" name="draft_reference" value="{{ $draft->reference }}"><input type="hidden" name="draft_token" value="{{ $draftToken }}">@endif
        <section class="wizard-panel" x-ref="step1" x-show="step === 1" x-cloak>
            <p class="eyebrow">Step 01 / Your details</p><h2 tabindex="-1">How should we<br>reach you?</h2><p class="wizard-help">Share the details you would like the membership team to use for your application.</p>
            <div class="form-grid"><div><label for="full_name">Full name <span>*</span></label><input id="full_name" name="full_name" value="{{ old('full_name', $draft?->full_name) }}" autocomplete="name" maxlength="160" required></div><div><label for="email">Email address <span>*</span></label><input id="email" name="email" type="email" value="{{ old('email', $draft?->email) }}" autocomplete="email" maxlength="190" required></div><div><label for="phone">Phone number <span>*</span></label><input id="phone" name="phone" type="tel" value="{{ old('phone', $draft?->phone) }}" autocomplete="tel" maxlength="40" required></div></div>
        </section>
        <section class="wizard-panel" x-ref="step2" x-show="step === 2" x-cloak>
            <p class="eyebrow">Step 02 / Member references</p><h2 tabindex="-1">Invite two people<br>who know your work.</h2><p class="wizard-help">Enter each current member’s name and membership number. We’ll email them a direct invitation to accept or decline your nomination.</p>
            @foreach([0 => 'First reference', 1 => 'Second reference'] as $index => $label)@php($reference = $draft?->references?->get($index))<fieldset class="reference-fieldset" x-data="{checking:false, status:'', valid:false, async verify(){const name=document.getElementById('ref_name_{{ $index }}').value.trim();const number=document.getElementById('ref_number_{{ $index }}').value.trim();if(!name||!number){this.status='';return;}this.checking=true;this.status='';try{const response=await fetch('{{ route('application.reference.validate') }}',{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('input[name=_token]').value},body:JSON.stringify({name,membership_number:number})});const result=await response.json();this.status=result.message;this.valid=!!result.valid;}catch(error){this.status='We could not verify these details right now. Please try again.';this.valid=false;}finally{this.checking=false;}}}"><legend>{{ $label }}</legend><div class="form-grid"><div><label for="ref_name_{{ $index }}">Member name <span>*</span></label><input id="ref_name_{{ $index }}" name="references[{{ $index }}][full_name]" value="{{ old("references.$index.full_name", $reference?->full_name) }}" autocomplete="name" required @change="status='';valid=false"></div><div><label for="ref_number_{{ $index }}">Membership number <span>*</span></label><input id="ref_number_{{ $index }}" name="references[{{ $index }}][membership_number]" value="{{ old("references.$index.membership_number", $reference?->membership_number) }}" autocomplete="off" required @blur="verify()" @input="status='';valid=false"></div></div><p class="reference-validation" :class="{'is-valid':valid,'is-invalid':status && !valid && !checking}" role="status" x-show="checking || status" x-text="checking ? 'Checking membership details…' : status" x-cloak></p></fieldset>@endforeach
        </section>
        <section class="wizard-panel" x-ref="step3" x-show="step === 3" x-cloak>
            <p class="eyebrow">Step 03 / Professional profile</p><h2 tabindex="-1">What do you<br>bring to the Den?</h2><p class="wizard-help">This helps the membership team understand your work and interests.</p>
            <div class="form-grid"><div><label for="company">Company or organisation <span>*</span></label><input id="company" name="company" value="{{ old('company', $draft?->company) }}" autocomplete="organization" maxlength="180" required></div><div><label for="job_title">Position or title <span>*</span></label><input id="job_title" name="job_title" value="{{ old('job_title', $draft?->job_title) }}" autocomplete="organization-title" maxlength="140" required></div><div><label for="industry">Industry <span>*</span></label><input id="industry" name="industry" value="{{ old('industry', $draft?->industry) }}" maxlength="140" required></div><div><label for="location">City or region <span>*</span></label><input id="location" name="location" value="{{ old('location', $draft?->location) }}" autocomplete="address-level2" maxlength="140" required></div></div>
            <label for="biography">A little about your work <span class="optional">Optional</span></label><textarea id="biography" name="biography" rows="4" maxlength="2000" placeholder="What are you working on, and what connections are you looking to build?">{{ old('biography', $draft?->biography) }}</textarea>
        </section>
        <section class="wizard-panel" x-ref="step4" x-show="step === 4" x-cloak>
            <p class="eyebrow">Step 04 / Review & submit</p><h2 tabindex="-1">A considered<br>application.</h2><p class="wizard-help">By submitting, you confirm your information is accurate and agree that the Den may contact you about this application. Your information will be handled under the society’s privacy terms.</p>
            <label for="package">Membership level <span>*</span></label><select id="package" name="membership_package_id" required><option value="">Choose a package</option>@foreach($packages as $package)<option value="{{ $package->id }}" data-slug="{{ $package->slug }}" @selected(old('membership_package_id', $draft?->membership_package_id ?? $selectedPackageId) == $package->id)>{{ $package->name }}</option>@endforeach</select>
            <div class="review-note"><span>APPLICATION REVIEW</span><p>Applications are reviewed by the Risk Team. Internal review notes are confidential and are not shared in the member portal.</p></div>
            <label class="consent-label"><input x-ref="consent" @change="$refs.consent.setCustomValidity('')" type="checkbox" name="consent" value="1" @checked(old('consent'))><span>I confirm the information is accurate and consent to the application review. I have read the <a href="{{ route('privacy') }}">Privacy Notice</a> and <a href="{{ route('terms') }}">Terms</a>. <b>*</b></span></label>
        </section>
        <section class="wizard-panel company-profile-panel" x-ref="step5" x-show="step === 5" x-cloak>
            <p class="eyebrow">Step 05 / Company profile</p><h2 tabindex="-1">Bring your work<br>into focus.</h2><p class="wizard-help">Tell us what your company does and share a profile so the membership team can understand the business behind your application.</p>
            <div class="company-profile-card"><span class="company-profile-tier">{{ strtoupper($chosenPackage?->name ?? 'GOLD / PLATINUM') }} MEMBERSHIP</span><p>Your company profile is shared privately with the membership team as part of your application.</p></div>
            <label for="company_description">What does your company do? <span>*</span></label><textarea id="company_description" name="company_description" rows="5" maxlength="2500" placeholder="Describe your products or services, the people you serve, and what makes your work distinctive." required>{{ old('company_description', $draft?->company_description) }}</textarea>
            <label for="employee_count">Number of employees <span>*</span></label><select id="employee_count" name="employee_count" required><option value="">Select a range</option>@foreach(['1-10' => '1–10 employees', '11-50' => '11–50 employees', '51-200' => '51–200 employees', '201-500' => '201–500 employees', '501-1000' => '501–1,000 employees', '1000+' => 'More than 1,000 employees'] as $value => $label)<option value="{{ $value }}" @selected(old('employee_count', $draft?->employee_count) === $value)>{{ $label }}</option>@endforeach</select>
            <label for="company_profile_file">Company profile <span>*</span></label><label class="company-dropzone" for="company_profile_file"><span class="dropzone-icon" aria-hidden="true">↑</span><strong>Choose a company profile to upload</strong><span>PDF, Word, PowerPoint or image · Up to 20 MB</span><input id="company_profile_file" name="company_profile_file" type="file" accept=".pdf,.doc,.docx,.ppt,.pptx" required @change="$refs.companyFilename.textContent = $event.target.files[0]?.name || 'PDF, Word, PowerPoint or image · Up to 20 MB'"></label><span x-ref="companyFilename" class="company-file-note">PDF, Word, PowerPoint or image · Up to 20 MB</span>
            @error('company_description')<span class="field-error">{{ $message }}</span>@enderror @error('employee_count')<span class="field-error">{{ $message }}</span>@enderror @error('company_profile_file')<span class="field-error">{{ $message }}</span>@enderror
        </section>
        <div class="wizard-controls"><button type="button" class="back-button" x-show="step > 1" @click="back()">← Previous step</button><span class="step-count" aria-live="polite" x-text="'Step 0' + step + ' of 0' + (isPremium() ? 5 : 4)"></span><button type="button" class="button" x-show="step < 4 || (step === 4 && isPremium())" @click="next()">Continue <span aria-hidden="true">→</span></button><button type="submit" class="button button-gold" x-show="(step === 4 && !isPremium()) || step === 5">Submit application <span aria-hidden="true">↗</span></button><button type="submit" name="save_draft" value="1" class="back-button save-draft-button" x-show="step === 4">Save progress and email me a return link</button></div>
    </form>
    </div>
</section>
@endsection
