@extends('layouts.public')
@section('title', 'Membership invoice')
@section('content')
<section class="page-hero"><p class="eyebrow">Premium Business Den / Membership</p><h1>Membership<br><em>invoice.</em></h1><p>{{ $invoice->application->package->name }} membership for {{ $invoice->application->full_name }}</p></section>
<section class="invoice-page"><div class="invoice-heading"><div><p class="eyebrow">Invoice reference</p><strong>{{ $invoice->reference }}</strong></div><span class="status-pill">{{ str($invoice->status)->replace('_', ' ')->title() }}</span></div><p class="invoice-dates">Issued {{ $invoice->issued_at->format('j F Y') }}@if($invoice->due_at) · Due {{ $invoice->due_at->format('j F Y') }}@endif</p><div class="invoice-items">@foreach($invoice->items as $item)<div><span>{{ $item->description }} × {{ $item->quantity }}</span><strong>{{ $invoice->currency }} {{ number_format((float) $item->amount, 2) }}</strong></div>@endforeach</div><div class="invoice-total"><span>Total due</span><strong>{{ $invoice->currency }} {{ number_format((float) $invoice->total, 2) }}</strong></div>
@foreach($invoice->payments as $payment)<p class="invoice-payment-note">Payment reference: <strong>{{ $payment->provider_reference }}</strong> · {{ str($payment->status)->title() }}</p>@endforeach
@if(in_array($invoice->status, ['pending', 'awaiting_payment'], true) && $invoice->payments->whereIn('status', ['pending', 'failed'])->isNotEmpty() && in_array(config('services.payment.driver'), ['daraja', 'mock'], true))<form method="POST" action="{{ $paymentUrl }}" class="invoice-payment-form">@csrf<label for="payment-phone">M-Pesa phone number</label><input id="payment-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="0712 345 678" value="{{ old('phone', $invoice->application->phone) }}" required>@error('phone')<p class="field-error">{{ $message }}</p>@enderror<button class="button" type="submit">Send payment prompt <span aria-hidden="true">→</span></button></form>@elseif($invoice->payments->contains(fn ($payment) => $payment->status === 'processing'))<p class="invoice-private-note">Payment request is processing. Complete the prompt on your phone and refresh this page for an updated status.</p>@endif
<p class="invoice-private-note">This private invoice page is provided for your membership application. Payment confirmation is recorded only after the configured payment service verifies it.</p></section>
@endsection
