@extends('layouts.public')
@section('title', 'Membership')
@section('content')
<section class="page-hero"><p class="eyebrow">Membership</p><h1>{!! nl2br(e($siteSettings->get('membership_heading') ?: "Connection with\nintention.")) !!}</h1><p>{{ $siteSettings->get('membership_body') ?: 'Choose the membership level that suits your ambitions. Package information is configurable by the Den and will be confirmed with applicants during review.' }}</p></section>
<section class="application-lookup" aria-labelledby="application-lookup-title"><div class="application-lookup-copy"><p class="eyebrow">Already applied?</p><h2 id="application-lookup-title">Check your application status.</h2><p>Enter the reference code you received after applying to see your latest status.</p></div><form method="POST" action="{{ route('application.lookup') }}" class="application-lookup-form">@csrf<label for="application-reference">Application reference</label><div class="application-lookup-input"><input id="application-reference" name="reference" type="text" value="{{ old('reference') }}" placeholder="PBD-2610-DIYZ3VO" autocomplete="off" required aria-describedby="application-reference-help"><button class="button button-gold" type="submit">Search status <span aria-hidden="true">→</span></button></div><small id="application-reference-help">Example: PBD-2610-DIYZ3VO</small>@error('reference')<span class="field-error" role="alert">{{ $message }}</span>@enderror</form></section>
<section class="membership-list"><div class="package-grid">@forelse($packages as $package)<x-package-card :package="$package" />@empty<p class="muted">Membership details are being prepared.</p>@endforelse</div></section>
<section class="membership-fit"><p class="eyebrow">Membership categories</p><h2>Three ways to<br><em>find your place.</em></h2><div class="membership-fit-grid"><article><span>01 / Diamond</span><h3>For independent ambition.</h3><p>A starting point for entrepreneurs, sole proprietors, smaller businesses, and employed or self-employed professionals seeking a trusted peer network.</p></article><article><span>02 / Gold</span><h3>For growing teams.</h3><p>For individuals and organizations looking to build relationships and exchange ideas across a broad professional community.</p></article><article><span>03 / Platinum</span><h3>For established leaders.</h3><p>The broadest membership category for leaders looking for deeper access to the society and its member network.</p></article></div></section>
<section class="page-body compact"><p>{{ $siteSettings->get('membership_disclaimer') ?: 'All applications are subject to review. Membership is confirmed after the application, document and payment steps are complete.' }}</p><a class="text-link" href="{{ route('how-to-join') }}">Read about the application process <span aria-hidden="true">→</span></a></section>
@endsection
