@extends('layouts.admin')
@section('title', 'Article categories and tags')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Content / Editorial setup</p><h1>Categories &amp; tags</h1><p>Organize the journal without changing application code.</p></div></div>
<div class="taxonomy-layout"><section class="admin-detail-card"><p class="eyebrow">Article categories</p><div class="taxonomy-category-list">@foreach($categories as $category)<form class="taxonomy-category-row" method="POST" action="{{ route('admin.taxonomy.categories.update', $category) }}">@csrf @method('PUT')<div class="form-grid"><div><label for="category_name_{{ $category->id }}">Name</label><input id="category_name_{{ $category->id }}" name="name" value="{{ $category->name }}" maxlength="100" required></div><div><label for="category_slug_{{ $category->id }}">Slug</label><input id="category_slug_{{ $category->id }}" name="slug" value="{{ $category->slug }}" maxlength="120"></div><div><label for="category_order_{{ $category->id }}">Order</label><input id="category_order_{{ $category->id }}" name="display_order" type="number" min="0" max="65535" value="{{ $category->display_order }}" required></div><div><label for="category_active_{{ $category->id }}">Visibility</label><select id="category_active_{{ $category->id }}" name="is_active"><option value="1" @selected($category->is_active)>Active</option><option value="0" @selected(!$category->is_active)>Inactive</option></select></div></div><label for="category_description_{{ $category->id }}">Description <span class="optional">{{ $category->articles_count }} articles</span></label><input id="category_description_{{ $category->id }}" name="description" value="{{ $category->description }}" maxlength="1000"><button class="review-secondary" type="submit">Save category</button></form>@endforeach</div>
<form class="taxonomy-new-category" method="POST" action="{{ route('admin.taxonomy.categories.store') }}">@csrf<p class="eyebrow">Add category</p><div class="form-grid"><div><label for="new_category_name">Name</label><input id="new_category_name" name="name" value="{{ old('name') }}" required></div><div><label for="new_category_slug">Slug <span class="optional">Optional</span></label><input id="new_category_slug" name="slug" value="{{ old('slug') }}"></div><div><label for="new_category_order">Display order</label><input id="new_category_order" name="display_order" type="number" min="0" max="65535" value="{{ old('display_order', 10) }}" required></div><div><label for="new_category_active">Visibility</label><select id="new_category_active" name="is_active"><option value="1">Active</option><option value="0">Inactive</option></select></div></div><label for="new_category_description">Description</label><input id="new_category_description" name="description" maxlength="1000"><button class="button" type="submit">Add category</button></form></section>
<aside class="admin-detail-card taxonomy-tag-panel"><p class="eyebrow">Article tags</p><form method="POST" action="{{ route('admin.taxonomy.tags.store') }}">@csrf<label for="tag_name">Add a tag</label><input id="tag_name" name="name" maxlength="100" required><button class="button button-full" type="submit">Save tag</button></form><ul class="taxonomy-tag-list">@forelse($tags as $tag)<li><span>{{ $tag->name }}</span><small>{{ $tag->articles_count }} articles</small></li>@empty<li><span>No tags yet.</span></li>@endforelse</ul></aside></div>
@foreach($errors->all() as $message)<p class="field-error">{{ $message }}</p>@endforeach
@endsection
