@extends('layouts.admin')
@section('title', 'Overview')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Premium Business Den / Administration</p><h1>Overview</h1><p>Application and membership activity at a glance.</p></div><a class="button" href="{{ route('admin.applications.index') }}">Review applications <span aria-hidden="true">→</span></a></div>
<div class="admin-metrics">
    <a class="admin-metric-link" href="{{ route('admin.applications.index') }}"><article><span>Applications to review</span><strong>{{ $pendingApplications }}</strong><small>Submitted, under review or in vetting</small></article></a>
    <a class="admin-metric-link" href="{{ route('admin.applications.index', ['status' => 'documents_required']) }}"><article><span>Awaiting documents</span><strong>{{ $awaitingDocuments }}</strong><small>Approved and collecting identity documents</small></article></a>
    <a class="admin-metric-link" href="{{ route('admin.applications.index') }}"><article><span>Awaiting payment</span><strong>{{ $awaitingPayments }}</strong><small>Invoice issued or payment pending</small></article></a>
    @if(auth()->user()->hasRole('super_administrator') || auth()->user()->hasRole('content_administrator'))
        <a class="admin-metric-link" href="{{ route('admin.articles.index', ['status' => 'pending_review']) }}"><article><span>Articles for review</span><strong>{{ $articlesForReview }}</strong><small>Pending editorial decision</small></article></a>
    @endif
    @if(auth()->user()->hasRole('super_administrator') || auth()->user()->hasRole('membership_administrator'))
        <a class="admin-metric-link" href="{{ route('admin.members.index', ['status' => 'active']) }}"><article><span>Active members</span><strong>{{ $activeMembers }}</strong><small>Current active accounts</small></article></a>
        @foreach($packages as $package)
            <a class="admin-metric-link" href="{{ route('admin.members.index', ['package' => $package->id, 'status' => 'active']) }}"><article><span>{{ $package->name }} members</span><strong>{{ $package->users_count }}</strong><small>Active membership</small></article></a>
        @endforeach
    @endif
</div>
<section class="admin-table-section"><div class="admin-section-heading"><div><p class="eyebrow">Latest activity</p><h2>Recent applications</h2></div><a class="text-link" href="{{ route('admin.applications.index') }}">View all <span aria-hidden="true">→</span></a></div>
@if($recentApplications->isEmpty())<div class="admin-empty"><strong>No applications yet</strong><p>New membership applications will appear here.</p></div>@else<div class="table-scroll"><table class="admin-table"><thead><tr><th>Applicant</th><th>Package</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>@foreach($recentApplications as $application)<tr><td><strong>{{ $application->full_name }}</strong><small>{{ $application->reference }}</small></td><td>{{ $application->package->name }}</td><td>{{ $application->submitted_at?->format('j M Y') }}</td><td><span class="status-pill">{{ $application->status->label() }}</span></td><td><a class="table-link" href="{{ route('admin.applications.show', $application) }}">Review →</a></td></tr>@endforeach</tbody></table></div>@endif
</section>
<div class="admin-table-section" style="margin-top:24px"><div class="admin-section-heading"><div><p class="eyebrow">Billing</p><h2>Recent payments</h2></div><a class="text-link" href="{{ route('admin.payments.index') }}">All payments →</a></div>@if($recentPayments->isEmpty())<div class="admin-empty"><strong>No payments yet</strong><p>Verified payment records will appear here.</p></div>@else<div class="table-scroll"><table class="admin-table"><thead><tr><th>Applicant</th><th>Invoice</th><th>Amount</th><th>Status</th><th>Received</th></tr></thead><tbody>@foreach($recentPayments as $payment)<tr><td>{{ $payment->invoice->application->full_name }}</td><td>{{ $payment->invoice->reference }}</td><td>{{ $payment->currency }} {{ number_format((float)$payment->amount, 2) }}</td><td>{{ str($payment->status)->title() }}</td><td>{{ $payment->confirmed_at?->format('j M Y') ?? '—' }}</td></tr>@endforeach</tbody></table></div>@endif</div>
<div class="admin-table-section" style="margin-top:24px"><div class="admin-section-heading"><div><p class="eyebrow">Membership</p><h2>Recent members</h2></div><a class="text-link" href="{{ route('admin.members.index') }}">All members →</a></div>@if($recentMembers->isEmpty())<div class="admin-empty"><strong>No members yet</strong><p>Activated memberships will appear here.</p></div>@else<div class="table-scroll"><table class="admin-table"><thead><tr><th>Member</th><th>Number</th><th>Package</th><th>Joined</th></tr></thead><tbody>@foreach($recentMembers as $member)<tr><td>{{ $member->name }}<small>{{ $member->email }}</small></td><td>{{ $member->membership?->number ?? '—' }}</td><td>{{ $member->membershipPackage?->name }}</td><td>{{ $member->membership?->started_at?->format('j M Y') ?? '—' }}</td></tr>@endforeach</tbody></table></div>@endif</div>
@endsection
