@extends('layouts.admin')
@section('title', 'Website settings')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Content / Website configuration</p><h1>Website settings</h1><p>Manage public page copy, FAQs, contact details and search defaults.</p></div></div>
<form class="cms-editor-form cms-editor-form-narrow event-editor" method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')<div class="article-editor-fields">
<p class="eyebrow">Homepage</p><label for="home_hero_title">Hero heading</label><textarea id="home_hero_title" name="home_hero_title" rows="2" maxlength="180">{{ old('home_hero_title', $settings->get('home_hero_title')) }}</textarea><label for="home_hero_intro">Hero introduction</label><textarea id="home_hero_intro" name="home_hero_intro" rows="3" maxlength="500">{{ old('home_hero_intro', $settings->get('home_hero_intro')) }}</textarea><label for="home_intro_heading">Introduction heading</label><textarea id="home_intro_heading" name="home_intro_heading" rows="2" maxlength="180">{{ old('home_intro_heading', $settings->get('home_intro_heading')) }}</textarea><label for="home_intro_body">Introduction copy</label><textarea id="home_intro_body" name="home_intro_body" rows="4" maxlength="1500">{{ old('home_intro_body', $settings->get('home_intro_body')) }}</textarea><label for="why_join_heading">Why join heading</label><input id="why_join_heading" name="why_join_heading" value="{{ old('why_join_heading', $settings->get('why_join_heading')) }}" maxlength="180"><label for="why_join_body">Why join copy</label><textarea id="why_join_body" name="why_join_body" rows="4" maxlength="1800">{{ old('why_join_body', $settings->get('why_join_body')) }}</textarea><label for="community_heading">Business community heading</label><input id="community_heading" name="community_heading" value="{{ old('community_heading', $settings->get('community_heading')) }}" maxlength="180"><label for="community_body">Business community copy</label><textarea id="community_body" name="community_body" rows="4" maxlength="1800">{{ old('community_body', $settings->get('community_body')) }}</textarea>
<p class="eyebrow">About and joining</p><label for="about_heading">About heading</label><textarea id="about_heading" name="about_heading" rows="2" maxlength="180">{{ old('about_heading', $settings->get('about_heading')) }}</textarea><label for="about_body">About copy</label><textarea id="about_body" name="about_body" rows="6" maxlength="3000">{{ old('about_body', $settings->get('about_body')) }}</textarea><label for="how_to_join_heading">How to join heading</label><textarea id="how_to_join_heading" name="how_to_join_heading" rows="2" maxlength="180">{{ old('how_to_join_heading', $settings->get('how_to_join_heading')) }}</textarea><label for="how_to_join_body">How to join copy</label><textarea id="how_to_join_body" name="how_to_join_body" rows="5" maxlength="2000">{{ old('how_to_join_body', $settings->get('how_to_join_body')) }}</textarea>
<p class="eyebrow">Membership page</p><label for="membership_heading">Page heading</label><textarea id="membership_heading" name="membership_heading" rows="2" maxlength="180">{{ old('membership_heading', $settings->get('membership_heading')) }}</textarea><label for="membership_body">Page introduction</label><textarea id="membership_body" name="membership_body" rows="4" maxlength="1500">{{ old('membership_body', $settings->get('membership_body')) }}</textarea><label for="membership_disclaimer">Membership information note</label><textarea id="membership_disclaimer" name="membership_disclaimer" rows="3" maxlength="800">{{ old('membership_disclaimer', $settings->get('membership_disclaimer')) }}</textarea>
<label for="faq_items">FAQs <span class="optional">One per line, format: Question | Answer</span></label><textarea id="faq_items" name="faq_items" rows="6" maxlength="6000">{{ old('faq_items', $settings->get('faq_items')) }}</textarea>
<p class="eyebrow">Contact and search</p><label for="public_contact_email">Public contact email</label><input id="public_contact_email" name="public_contact_email" type="email" value="{{ old('public_contact_email', $settings->get('public_contact_email')) }}" maxlength="190"><label for="public_contact_phone">Public contact phone</label><input id="public_contact_phone" name="public_contact_phone" type="tel" value="{{ old('public_contact_phone', $settings->get('public_contact_phone')) }}" maxlength="40"><label for="office_location">Office location</label><input id="office_location" name="office_location" value="{{ old('office_location', $settings->get('office_location')) }}" maxlength="180"><label for="contact_recipient_email">Enquiry notification inbox <span class="optional">Private · Defaults to CONTACT_TO_ADDRESS</span></label><input id="contact_recipient_email" name="contact_recipient_email" type="email" value="{{ old('contact_recipient_email', $settings->get('contact_recipient_email')) }}" maxlength="190"><label for="default_seo_title">Default page title</label><input id="default_seo_title" name="default_seo_title" value="{{ old('default_seo_title', $settings->get('default_seo_title')) }}" maxlength="180"><label for="default_seo_description">Default search description</label><textarea id="default_seo_description" name="default_seo_description" rows="3" maxlength="300">{{ old('default_seo_description', $settings->get('default_seo_description')) }}</textarea>@foreach($errors->all() as $message)<span class="field-error">{{ $message }}</span>@endforeach</div><button class="button" type="submit">Save website settings <span aria-hidden="true">→</span></button></form>
@endsection
