@extends('layouts.admin')
@section('title', 'Application '.$application->reference)
@section('content')
<div class="admin-breadcrumb"><a href="{{ route('admin.applications.index') }}">Applications</a><span>/</span><span>{{ $application->reference }}</span></div>
@php($applicationInitials = collect(preg_split('/\s+/', trim($application->full_name)))->filter()->take(2)->map(fn ($part) => mb_substr($part, 0, 1))->implode(''))
<div class="application-admin-heading">
    <div class="application-admin-person">
        <span class="application-admin-avatar" aria-hidden="true">{{ $applicationInitials }}</span>
        <div><p class="eyebrow">Membership application <span class="application-reference">{{ $application->reference }}</span></p><h1>{{ $application->full_name }}</h1><p class="application-admin-meta"><span>{{ $application->package->name }} membership</span><i aria-hidden="true"></i><span>Submitted {{ $application->submitted_at?->format('j F Y · H:i') }}</span></p></div>
    </div>
    <div class="application-admin-current-status"><small>APPLICATION STATUS</small><span class="status-pill status-large">{{ $application->status->label() }}</span></div>
</div>
<div class="application-admin-grid"><div class="application-admin-main">
    <section class="admin-detail-card"><p class="eyebrow">Applicant profile</p><dl class="detail-grid"><div><dt>Email</dt><dd><a href="mailto:{{ $application->email }}">{{ $application->email }}</a></dd></div><div><dt>Phone</dt><dd>{{ $application->phone }}</dd></div><div><dt>Company</dt><dd>{{ $application->company }}</dd></div><div><dt>Position</dt><dd>{{ $application->job_title }}</dd></div><div><dt>Industry</dt><dd>{{ $application->industry }}</dd></div><div><dt>Location</dt><dd>{{ $application->location }}</dd></div><div class="detail-wide"><dt>Professional introduction</dt><dd>{{ $application->biography ?: 'No introduction provided.' }}</dd></div></dl></section>
    <section class="admin-detail-card"><p class="eyebrow">Member references</p><div class="reference-admin-list">@foreach($application->references as $reference)<article><strong>{{ $reference->full_name }}</strong><span>{{ $reference->email }}</span>@if($reference->phone)<span>{{ $reference->phone }}</span>@endif<span class="reference-verification">{{ $reference->member_user_id ? 'Matched to an active member' : 'Requires member verification' }}</span></article>@endforeach</div></section>
    @if($application->company_description || $application->employee_count)<section class="admin-detail-card"><p class="eyebrow">Company profile</p><dl class="detail-grid"><div><dt>Employees</dt><dd>{{ $application->employee_count ?? '—' }}</dd></div><div class="detail-grid-wide"><dt>Business overview</dt><dd>{{ $application->company_description ?? '—' }}</dd></div></dl></section>@endif
    @if($application->documents->isNotEmpty())<section class="admin-detail-card"><p class="eyebrow">Applicant documents <span class="private-label">Private documents</span></p><div class="applicant-documents">@foreach($application->documents as $document)<article class="applicant-document"><div><strong>{{ $document->document_type === 'company_profile' ? 'Company profile' : ($document->document_type === 'photo' ? 'Passport-size photograph' : ($document->identity_type === 'passport' ? 'Travel passport' : 'National ID')) }}</strong><span>{{ $document->original_name }} · {{ number_format($document->size_bytes / 1024, 0) }} KB</span><span class="status-pill">{{ $document->status->label() }}</span><a class="table-link" href="{{ route('admin.documents.show', $document) }}" target="_blank" rel="noopener">Open securely ↗</a></div>@if($document->document_type !== 'company_profile' && (auth()->user()->hasRole('super_administrator') || auth()->user()->hasRole('membership_administrator')))<form method="POST" action="{{ route('admin.documents.decide', $document) }}">@csrf @method('PATCH')<label for="doc_status_{{ $document->id }}">Review outcome</label><select id="doc_status_{{ $document->id }}" name="status"><option value="approved">Approve</option><option value="rejected">Reject</option><option value="replacement_requested">Request replacement</option></select><label for="doc_note_{{ $document->id }}">Replacement guidance for applicant <span class="optional">Optional</span></label><textarea id="doc_note_{{ $document->id }}" name="review_note" rows="2" maxlength="2000"></textarea><button class="review-secondary" type="submit">Save document decision</button></form>@endif</article>@endforeach</div></section>@endif
    @if($application->invoice)<section class="admin-detail-card"><p class="eyebrow">Invoice &amp; payment</p><dl class="detail-grid"><div><dt>Invoice reference</dt><dd>{{ $application->invoice->reference }}</dd></div><div><dt>Invoice status</dt><dd>{{ str($application->invoice->status)->replace('_', ' ')->title() }}</dd></div><div><dt>Total</dt><dd>{{ $application->invoice->currency }} {{ number_format((float) $application->invoice->total, 2) }}</dd></div><div><dt>Issued</dt><dd>{{ $application->invoice->issued_at->format('j M Y') }}</dd></div>@foreach($application->invoice->payments as $payment)<div><dt>Payment status</dt><dd>{{ str($payment->status)->title() }} · {{ $payment->provider }}</dd></div><div><dt>Payment reference</dt><dd>{{ $payment->provider_reference }}</dd></div>@endforeach</dl></section>@endif
    <section class="admin-detail-card"><p class="eyebrow">Review timeline</p><ol class="admin-timeline">@foreach($application->statusHistory->sortBy('occurred_at') as $event)<li><span class="timeline-dot"></span><div><strong>{{ $event->to_status->label() }}</strong><small>{{ $event->occurred_at->format('j M Y · H:i') }}@if($event->actor) · {{ $event->actor->name }}@else · Applicant @endif</small></div></li>@endforeach</ol></section>
    <section class="admin-detail-card"><p class="eyebrow">Internal review notes <span class="private-label">Private to authorized team</span></p>@forelse($application->internalNotes->sortByDesc('created_at') as $note)<article class="internal-note"><p>{{ $note->body }}</p><small>{{ $note->author->name }} · {{ $note->created_at->format('j M Y, H:i') }}</small></article>@empty<p class="admin-muted">No internal notes have been recorded.</p>@endforelse</section>
    </div>
    <aside class="application-admin-side"><section class="admin-detail-card review-actions"><p class="eyebrow">Review action</p><div class="review-current-status"><span>Current status</span><strong>{{ $application->status->label() }}</strong></div><form method="POST" action="{{ route('admin.applications.transition', $application) }}">@csrf @method('PATCH')<label for="status">Next status</label><select id="status" name="status" required><option value="">Choose next status</option>@foreach($statuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select><label for="note">Internal note <span class="optional">Optional</span></label><textarea id="note" name="note" rows="5" maxlength="3000" placeholder="Record relevant review context for authorized staff.">{{ old('note') }}</textarea>@error('status')<span class="field-error">{{ $message }}</span>@enderror<button class="button button-full" type="submit">Save review update <span aria-hidden="true">→</span></button></form></section>@if($application->status->value === 'documents_required' && (auth()->user()->hasRole('super_administrator') || auth()->user()->hasRole('membership_administrator')))<section class="admin-detail-card upload-link-panel"><p class="eyebrow">Secure upload link</p><p>Current link expiry: {{ $application->document_upload_expires_at?->format('j M Y, H:i') ?? 'Not set' }}</p><form method="POST" action="{{ route('admin.applications.documents.resend', $application) }}">@csrf<button class="review-secondary" type="submit">Send a fresh upload link <span aria-hidden="true">↗</span></button></form></section>@endif<p class="privacy-callout"><span aria-hidden="true">◆</span> Applicant information and internal notes are visible only to authorized administrators.</p></aside>
</div>
@endsection
