@extends('layouts.admin')
@section('title', 'Compose member notice')
@section('content')
<div class="admin-breadcrumb"><a href="{{ route('admin.announcements.index') }}">Member notices</a><span>/</span><span>{{ $announcement->exists ? 'Edit draft' : 'Compose' }}</span></div><div class="admin-page-heading"><div><p class="eyebrow">Member communication</p><h1>{{ $announcement->exists ? 'Edit draft notice' : 'Compose a notice' }}</h1><p>Published notices are delivered to each active recipient’s in-app inbox.</p></div></div>
<form class="cms-editor-form cms-editor-form-narrow event-editor" method="POST" action="{{ $announcement->exists ? route('admin.announcements.update', $announcement) : route('admin.announcements.store') }}">@csrf @if($announcement->exists)@method('PUT')@endif<div class="article-editor-fields"><label for="title">Notice title <span>*</span></label><input id="title" name="title" value="{{ old('title', $announcement->title) }}" maxlength="180" required><label for="body">Message <span>*</span></label><textarea id="body" name="body" rows="8" maxlength="5000" required>{{ old('body', $announcement->body) }}</textarea>
<div x-data="{ target: '{{ old('target', $announcement->target ?? 'all_members') }}' }"><label for="target">Audience <span>*</span></label><select id="target" name="target" x-model="target" required><option value="all_members">All active members</option><option value="packages">Selected packages</option><option value="selected">Selected members</option></select>
<div class="event-package-options" x-show="target === 'packages'" x-cloak><p class="eyebrow">Membership packages</p>@foreach($packages as $package)<label class="event-package-option"><input type="checkbox" name="package_ids[]" value="{{ $package->id }}" @checked(in_array($package->id, array_map('intval', old('package_ids', $announcement->package_ids ?? [])), true))><span>{{ $package->name }}</span></label>@endforeach</div>
<div class="event-member-options" x-show="target === 'selected'" x-cloak><label for="member_ids">Active members <span>*</span></label>@php($selectedMemberIds = old('member_ids', $announcement->exists ? $announcement->selectedMembers->pluck('id')->all() : []))<select id="member_ids" name="member_ids[]" multiple size="8">@foreach($members as $member)<option value="{{ $member->id }}" @selected(in_array($member->id, array_map('intval', $selectedMemberIds), true))>{{ $member->name }} · {{ $member->email }}</option>@endforeach</select><p class="article-editor-note">Use Ctrl or Command to select more than one member.</p></div></div>
@foreach($errors->all() as $message)<span class="field-error">{{ $message }}</span>@endforeach
</div><div class="cms-form-actions"><button class="button" type="submit" name="action" value="publish">Publish and deliver <span aria-hidden="true">→</span></button><button class="review-secondary" type="submit" name="action" value="draft">Save draft</button></div></form>
@endsection
