@extends(auth()->user()?->hasActiveMembership() ? 'layouts.member' : 'layouts.public')
@section('title', 'Business insights')
@section('meta_description', 'Ideas and perspectives from Premium Business Den authors.')
@section('content')
@unless(auth()->user()?->hasActiveMembership())<section class="directory-heading journal-directory-heading"><div class="journal-directory-inner"><div><p class="eyebrow"><span class="eyebrow-line"></span>The Den / Journal</p><h1>Ideas for<br><em>what’s next.</em></h1><p>Perspectives and practical insight from the people who make business happen.</p></div><span class="listing-seal" aria-hidden="true"><b>PB</b><i></i><small>Journal</small></span></div></section>@endunless
<section class="article-index journal-index"><form class="article-search" role="search" aria-label="Search published articles" method="GET" action="{{ route('articles.index') }}"><label><span class="sr-only">Search articles</span><input type="search" name="search" value="{{ request('search') }}" placeholder="Search article titles or excerpts"></label><button class="button" type="submit">Search <span aria-hidden="true">↗</span></button></form>
    @if($articles->isEmpty())<div class="directory-empty"><span class="empty-emblem">P<span>·</span>D</span><h2>{{ request('search') ? 'No articles found.' : 'New perspectives are on the way.' }}</h2><p>{{ request('search') ? 'Try another search.' : 'Published articles will appear here as our authors share their work.' }}</p></div>@else<div class="journal-results-meta"><span>{{ $articles->total() }} {{ $articles->total() === 1 ? 'article' : 'articles' }}{{ request('search') ? ' matching “'.request('search').'”' : '' }}</span><span>Perspectives from the Den</span></div><div class="article-grid">@foreach($articles as $article)<article class="article-card journal-card">@if($article->featured_image_path)<img class="article-card-image" src="{{ Storage::disk('public')->url($article->featured_image_path) }}" alt="{{ $article->title }}" loading="lazy" decoding="async">@endif<p class="eyebrow">{{ $article->category?->name ?? 'The Den' }} <span>·</span> {{ $article->published_at->format('j F Y') }}</p><h2><a href="{{ route('articles.show', $article->slug) }}">{{ $article->title }}</a></h2><p>{{ $article->excerpt }}</p><div class="article-byline">{{ $article->author->name }}</div><a class="text-link" href="{{ route('articles.show', $article->slug) }}">Read article <span aria-hidden="true">↗</span></a></article>@endforeach</div>{{ $articles->links() }}@endif
</section>
@if(auth()->user()?->hasActiveMembership())<section class="directory-heading journal-directory-heading"><div class="journal-directory-inner"><div><p class="eyebrow"><span class="eyebrow-line"></span>Member space / Journal</p><h1>Ideas for<br><em>what’s next.</em></h1><p>Perspectives and practical insight from the people who make business happen.</p></div><span class="listing-seal" aria-hidden="true"><b>PB</b><i></i><small>Journal</small></span></div></section>@endif
@endsection
