@extends('layouts.admin')
@section('title', $event->exists ? 'Edit event' : 'Create event')
@section('content')
<div class="admin-breadcrumb"><a href="{{ route('admin.events.index') }}">Events</a><span>/</span><span>{{ $event->exists ? 'Edit event' : 'New event' }}</span></div>
<div class="admin-page-heading"><div><p class="eyebrow">Society calendar / Event management</p><h1>{{ $event->exists ? 'Edit event' : 'Create event' }}</h1><p>Only published events are shown. Visibility is enforced for member pages.</p></div></div>
<form class="cms-editor-form cms-editor-form-narrow event-editor" method="POST" enctype="multipart/form-data" action="{{ $event->exists ? route('admin.events.update', $event) : route('admin.events.store') }}">@csrf @if($event->exists)@method('PUT')@endif
    <div class="article-editor-fields"><label for="title">Event title <span>*</span></label><input id="title" name="title" value="{{ old('title', $event->title) }}" maxlength="180" required>@error('title')<span class="field-error">{{ $message }}</span>@enderror
    <div class="form-grid"><div><label for="slug">URL slug <span class="optional">Optional</span></label><input id="slug" name="slug" value="{{ old('slug', $event->slug) }}" maxlength="190"></div><div><label for="location">Location <span>*</span></label><input id="location" name="location" value="{{ old('location', $event->location) }}" maxlength="180" required></div></div>
    <label for="description">Description <span>*</span></label><textarea id="description" name="description" rows="9" maxlength="12000" required>{{ old('description', $event->description) }}</textarea><label for="featured_image">Featured image <span class="optional">JPG, PNG or WebP · 5 MB max</span></label><input id="featured_image" name="featured_image" type="file" accept="image/jpeg,image/png,image/webp">@if($event->featured_image_path)<img class="article-image-preview" src="{{ Storage::disk('public')->url($event->featured_image_path) }}" alt="Current event image">@endif
    <div class="form-grid"><div><label for="starts_at">Starts at <span>*</span></label><input id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at', $event->starts_at?->format('Y-m-d\TH:i')) }}" required></div><div><label for="ends_at">Ends at <span class="optional">Optional</span></label><input id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at', $event->ends_at?->format('Y-m-d\TH:i')) }}"></div></div>
    <div x-data="{ visibility: '{{ old('visibility', $event->visibility ?? 'public') }}' }"><label for="visibility">Who can see this event? <span>*</span></label><select id="visibility" name="visibility" x-model="visibility"><option value="public">Public</option><option value="members">All active members</option><option value="packages">Selected packages</option></select>
    <div class="event-package-options" x-show="visibility === 'packages'" x-cloak><p class="eyebrow">Choose packages</p>@foreach($packages as $package)<label class="event-package-option"><input type="checkbox" name="package_ids[]" value="{{ $package->id }}" @checked(in_array($package->id, array_map('intval', old('package_ids', $event->package_ids ?? [])), true))><span>{{ $package->name }}</span></label>@endforeach</div></div>
    <label for="registration_url">Registration link <span class="optional">Optional · HTTPS</span></label><input id="registration_url" name="registration_url" type="url" value="{{ old('registration_url', $event->registration_url) }}" maxlength="2048">
    <label for="registration_information">Invite or registration information <span class="optional">Optional</span></label><textarea id="registration_information" name="registration_information" rows="3" maxlength="3000">{{ old('registration_information', $event->registration_information) }}</textarea>
    <label for="status">Publication status <span>*</span></label><select id="status" name="status" required><option value="draft" @selected(old('status', $event->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $event->status) === 'published')>Published</option><option value="cancelled" @selected(old('status', $event->status) === 'cancelled')>Cancelled</option></select>
    @foreach($errors->all() as $message)<span class="field-error">{{ $message }}</span>@endforeach
    </div><button class="button" type="submit">Save event <span aria-hidden="true">→</span></button>
</form>
@endsection
